name       : bro
version    : 4.0.5
release    : 9
source     :
    - git|https://github.com/bro/bro : v4.0.5
license    : BSD-3-Clause
component  : security
summary    : Bro is a powerful framework for network analysis and security monitoring
description: |
    Bro is a powerful framework for network analysis and security monitoring
builddeps  :
    - pkgconfig(libpcap)
    - pkgconfig(python3)
setup      : |
    mkdir build
    cd build
    %cmake ..
build      : |
    %make -C build
install    : |
    %make_install -C build
