name       : bro
version    : 2.6.1
release    : 4
source     :
    - git|https://github.com/bro/bro : v2.6.1
license    : BSD-3-Clause
component  : security
summary    : Bro is a powerful framework for network analysis and security monitoring
description: |
    Bro is a powerful framework for network analysis and security monitoring
builddeps  :
    - libpcap-devel
setup      : |
    mkdir build
    cd build
    %cmake ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
